name: doxygen
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_doxygen: # Give the job a descriptive name (mapping key)
    runs-on: ubuntu-latest # Specify the runner environment
    permissions:
      contents: write
      pages: write # Good practice to include this if deploying to GH Pages
      id-token: write # Required by the peaceiris action
    steps:
      # Checkout the repository first (essential for actions to access your code)
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Doxygen Action
        # You may pin to the exact commit or the version.
        uses: mattnotmitt/doxygen-action@1.9.8
        with:
          # Path to Doxyfile
          doxyfile-path: ./Doxyfile # default is ./Doxyfile
          # Working directory
          working-directory: . # default is .
          # Generate latex documentation
          enable-latex: false # optional (default is false)
          # Extra alpine packages for the build environment

      - name: Commit and push ONLY the documentation folder
        # We use a condition to only deploy when pushing to the main branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Name of the branch you want to push to
          publish_dir: ./doxygen # Only the contents of the 'doxygen' directory will be pushed
          commit_message: "Auto-generated Doxygen documentation update"
